***Задание на 14 января***

1) Импортируйте numpy как np.

In [1]:
import numpy as np

2) Создайте одномерный массив чисел от 0 до 9.

In [3]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3) Создайте логический массив размером 3 × 3 из всех True.

In [30]:
b=np.array(range(1,10), dtype=bool).reshape(3,3)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
b=np.full((3,3), True)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
b=np.ones((3,3), dtype=bool)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4) Извлеките все нечетные числа из arr.

In [38]:
odd_number_filter=(a%2)!=0
odd_number_filter

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [39]:
a[odd_number_filter]


array([1, 3, 5, 7, 9])

5) Замените все нечетные числа на -1.

In [40]:
a[odd_number_filter]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**Кейс про банк**

In [41]:
import pandas as pd

In [42]:
url="https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/data/bank-full.csv"

In [43]:
bank = pd.read_csv(url, delimiter=';')
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [44]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


1) Определите средний возраст клиентов банка

In [46]:
round(bank['age'].mean(), 2)

40.94

2) Определите профессии клиентов банка, которые имеют семейный статус 'single'

In [47]:
filter=bank['marital']=='single'

In [50]:
bank[filter]['job'].unique()

array(['technician', 'unknown', 'management', 'admin.', 'blue-collar',
       'entrepreneur', 'retired', 'unemployed', 'services',
       'self-employed', 'student', 'housemaid'], dtype=object)

In [49]:
bank[['job', 'marital']].where(filter, inplace = False).dropna()

job marital
0             NaN     NaN
1      technician  single
2             NaN     NaN
3             NaN     NaN
4         unknown  single
...           ...     ...
45206         NaN     NaN
45207         NaN     NaN
45208         NaN     NaN
45209         NaN     NaN
45210         NaN     NaN

[45211 rows x 2 columns]